name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo
        ports: ["27017:27017"]
    strategy:
      matrix:
        service: [order-service, invoice-service]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install & Test
        run: |
          cd ${{ matrix.service }}
          npm install
          npm run test
